### ISSUE TITLE
Don't rely on `prime`

### ISSUE THREAD

**Issue by marcandre** [noahgibbs/ractor_basic_benchmarks#2]
Heads up: `Integer#prime?` has been optimized in Ruby 3, so no benchmark should rely on that, at least to compare between 3.0 and other versions...

**Comment by noahgibbs** [comment]
Ah, interesting. Maybe I was reading the old implementation. Makes sense that Koichi fixed it up while using it for so many benchmarks :-)

**Comment by marcandre** [comment]
Actually you can [thank Stephen Blackstone and myself](https://github.com/ruby/ruby/commit/1866d483dce614a02c5186bd0588b48a5041e55e) for that 😅

**Comment by marcandre** [comment]
BTW, [this bug report](https://bugs.ruby-lang.org/issues/17497) may interest you
